# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c7d2898c3982a09423bee865284b420e2afe4e4fae3ecb789680254884091556a80e930c106e94b7f4173e8259d9c871e8675ced8768288d53ba46183e4e92

test:
  secret_key_base: f328fac8ddf1b6a70871ce88cfda3448d4174497c2398cee70bfd5a716a6862b19d094d2a32f0326fbc8aa12e5d8acf3a0f650ae64281e6f5352ea83e3689d9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
